#!/bin/python3
import re, os
import shutil, atexit
import sys, termios, tty
from threading import Thread
from time import sleep

txt = """
.s5SSSs.                                              .s5SSSs.                                    
      SS. .s        .s5SSSs.  .s5SSSSs. .s5SSSs.            SS. .s    s.  .s5SSSs.  s.  .s5SSSs.  
sS    S%S                 SS.       SSS       SS.     sS    `:;       SS.       SS. SS.       SS. 
SS    S%S sS        sS    S%S     sSSS  sS    `:;     SS        sS    S%S sS    S%S S%S sS    S%S 
SS .sSSS  SS        SSSs. S%S    sSS"   SSSs.         `:;;;;.   SS    S%S SS    S%S S%S SS    S%S 
SS    S%S SS        SS    S%S   sSS     SS                  ;;. SS    S%S SS    S%S S%S SS    S%S 
SS    `:; SS        SS    `:;  sSS      SS                  `:; SS    `:; SS    `:; `:; SS    `:; 
SS    ;,. SS    ;,. SS    ;,. sSS       SS    ;,.     .,;   ;,. SS    ;,. SS    ;,. ;,. SS    ;,. 
`:;;;;;:' `:;;;;;:' :;    ;:' `:;;;;;:' `:;;;;;:'     `:;;;;;:' `:;;;;;:' ;;;;;;;:' ;:' `:;;;;;:' 
""" # Font used: amcslash
txt = txt[1:-1]+'\033[0m'

txt = re.sub('([5S]+)', '\033[31m\\1', txt)
txt = re.sub(r'(%+)', '\033[35m\\1', txt)
txt = re.sub('([s.]+)', '\033[91m\\1', txt)
txt = re.sub('([`:"\']+)', '\033[92m\\1', txt)
txt = re.sub('([;,]+)', '\033[32m\\1', txt)

print(txt)
print()

def bracketulate(txt):
    return f'\033[93m[{txt}\033[93m]\033[0m'

basetxts = {
    'info': '\033[38;5;69m~',
    'error': '\033[38;5;160m-',
    'good': '\033[38;5;28m+',
    'warn': '\033[38;5;202;52;1m!',
    'mid': '\033[38;2;193;156;0m=',
    'bad': '\033[38;5;9m:('
}

txts = {
    i: bracketulate(basetxts[i])+' ' for i in basetxts
    #i: basetxts[i]+'\033[0m ' for i in basetxts
}

def highlight(txt):
    return '\033[38;5;172m' + txt + '\033[0m'

class Spinner:
    spins = ['|', '/', '-', '\\']

    @classmethod
    def spinning_cursor(cls):
        while 1:
            for cursor in cls.spins:
                yield bracketulate('\033[38;5;166m'+cursor)

    def __init__(self, txt, delay=0.1):
        self.txt = txt
        self.delay = delay
        self.running = False
        self.requestStop = False
        self.t = None

    def spinner_task(self):
        self.running = True
        spinner_generator = self.spinning_cursor()
        print()
        while not self.requestStop:
            print('\033[F' + self.txt + next(spinner_generator))
            sleep(self.delay)
        self.running = False

    def __enter__(self):
        self.requestStop = False
        self.started = False
        self.t = Thread(target=self.spinner_task, daemon=True).start()
        return self

    def __exit__(self, exception, value, tb):
        self.requestStop = True
        while self.running:
            pass

# Save the original terminal attributes globally so we can restore them later
orig_termios = None

def enable_input_mode():
    global orig_termios
    fd = sys.stdin.fileno()
    orig_termios = termios.tcgetattr(fd)
    tty.setcbreak(fd) # or tty.setraw(fd) if you prefer raw mode

def disable_input_mode():
    global orig_termios
    if orig_termios:
        termios.tcsetattr(sys.stdin.fileno(), termios.TCSAFLUSH, orig_termios)
        orig_termios = None

atexit.register(disable_input_mode)

def getch():
    if orig_termios is None:
        enable_input_mode()
    try:
        return sys.stdin.read(1)
    finally:
        disable_input_mode()

def options(title, opts, default=0):
    prevchrs = 0
    opt = default

    def print_opts():
        print(f'{bracketulate('\033[38;5;166m?')} \033[92;11m{title}: \033[94;5m{opts[opt]}\033[0m'+' '*max(len(i) for i in opts))
        for i in range(len(opts)):
            t = opts[i]
            if i == opt:
                print(f'\033[94;1;3m>  {t}\033[0m')
            else:
                print(f'   {t}\033[0m')
    print_opts()

    def update_opts():
        nonlocal prevchr
        prevchr = 0
        print(f'\033[{len(opts)+2}B', end='')
        print('\033[F'*(len(opts)+2))
        print_opts()
        print('\033[F'*(len(opts)-opt)+'\033[2C', end='')
    
    update_opts()
    
    while True:
        char = getch()
        if char == '\x1b':
            prevchr = 1
        elif char == '[' and prevchr == 1:
            prevchr = 2
        elif char == 'A' and prevchr == 2 and opt > 0:
            opt -= 1
            update_opts()
        elif char == 'B' and prevchr == 2 and opt < len(opts)-1:
            opt += 1
            update_opts()
        elif char == '5' and prevchr == 2:
            opt = 0
            update_opts()
        elif char == '6' and prevchr == 2:
            opt = len(opts)-1
            update_opts()
        elif char == '\n':
            break
        else:
            prevchr = 0
    print(f'\033[F\033[{len(opts)+2}B', end='')
    disable_input_mode()
    return opt

def ask(title, keyOpts, newline=True):
    print(f'{bracketulate('\033[38;5;166m?')} \033[92m{title}{"\n" if newline else " "}\033[94;5m> ', end='')
    while True:
        k = getch()
        if k in keyOpts:
            print(f'\033[94m{k}\033[0m')
            disable_input_mode()
            return keyOpts.index(k)

def askInp(title, newline=True):
    disable_input_mode()
    return input(f'{bracketulate('\033[38;5;166m?')} \033[92m{title}{"\n" if newline else " "}\033[94;5m> ')

l = ['Make a new project here 📁', 'Make a new project in a subdirectory 🗃️', 'Open docs 📚️', '\033[35mQuit 👋']
chosen = options('What would you like to do?', l)

def makeNewProject(where):
    print(txts['info']+'Making project in '+where+'...')
    print(txts['bad']+'NOTIMPLEMENTED')

if chosen == 0:
    if os.listdir(os.getcwd()) != []:
        resp = options(f'Path {os.getcwd()} has things in it! What do you want to do?', ['Override it & delete everything in it 🔥', '\033[35mQuit 👋'])
        if resp == 0:
            if ask(highlight(f'Are you sure you want to override the folder {os.getcwd()} and delete everything in it?')+' [y/n]', ['y', 'Y', 'n', 'N']) in (0, 1):
                print(txts['warn']+'Deleting folder '+os.getcwd()+'...')
                shutil.rmtree(os.getcwd())
                os.mkdir(os.getcwd())
                makeNewProject(os.getcwd())
            else:
                print(txts['good']+'OK, quitting!')
                complete = True
        else:
            print(txts['good']+'OK, quitting!')
            complete = True
    else:
        makeNewProject(os.getcwd())
elif chosen == 1:
    complete = False
    while not complete:
        where = os.path.join(os.getcwd(), askInp('What would you like to name the folder? (Type nothing to exit)').replace('/', '_'))
        if not where.replace('/', ''):
            print(txts['good']+'OK, exiting!')
            complete = True
            continue
        if os.path.exists(where):
            if os.listdir(where) != []:
                resp = options(f'Path %s exists and has things in it! What do you want to do?'%where, ['Override it & delete everything in it 🔥', 'Choose again 🤔', '\033[35mQuit 👋'])
                if resp == 0:
                    if ask(highlight(f'Are you sure you want to override the folder {where} and delete everything in it?')+' [y/n]', ['y', 'Y', 'n', 'N'], False) in (0, 1):
                        print(txts['warn']+'Deleting folder '+where+'...')
                        shutil.rmtree(where)
                        os.mkdir(where)
                        makeNewProject(where)
                elif resp == 1:
                    pass
                else:
                    print(txts['good']+'OK, quitting!')
                    complete = True
            else:
                print(txts['info']+'Directory %s exists, but is empty. Using that.'%where)
                makeNewProject(where)
        else:
            os.mkdir(where)
            makeNewProject(where)
elif chosen == 2:
    if ask('Would you like to open the offline 🖥️  docs (1) or the online 🌐 docs (2)?', ['1', '2'], False) == 0:
        print(txts['good']+'OK! Opening offline docs...')
        print(txts['bad']+'NOTIMPLEMENTED')
    else:
        print(txts['good']+'OK! Opening online docs...')
        import webbrowser
        webbrowser.open('https://tsunami014.gitbook.io/blaze-sudios')
else: # quit
    print(txts['good']+'OK, quitting!')
