import numpy as np

def _drawCirc(arr: np.ndarray, pos: np.ndarray, radius: int, thickness: int, col: np.ndarray):
    ...

def _drawElipse(arr: np.ndarray, pos: np.ndarray, xradius: int, yradius: int, rotation: float, thickness: int, col: np.ndarray):
    ...

def _drawRect(arr: np.ndarray, pos: np.ndarray, sze: np.ndarray, thickness: int, round: int, col: np.ndarray):
    ...

def _drawThickLine(arr: np.ndarray, p1: np.ndarray, p2: np.ndarray, thickness: int, colour: np.ndarray):
    ...


# This file was generated by stubgen-pyx v0.1.3