from sdl2 import *
speshs = {
    " ": SDL_SCANCODE_SPACE,
    "space": SDL_SCANCODE_SPACE,
    "\t": SDL_SCANCODE_TAB,
    "tab": SDL_SCANCODE_TAB,
    "enter": SDL_SCANCODE_RETURN,
    "return": SDL_SCANCODE_RETURN,
    "newline": SDL_SCANCODE_RETURN,
    "\n": SDL_SCANCODE_RETURN,
    "\r": SDL_SCANCODE_RETURN,
    "backspace": SDL_SCANCODE_BACKSPACE,
    "back": SDL_SCANCODE_BACKSPACE,
    "\b": SDL_SCANCODE_BACKSPACE,
    "escape": SDL_SCANCODE_ESCAPE,
    "esc": SDL_SCANCODE_ESCAPE,
    "\033": SDL_SCANCODE_ESCAPE,
    "insert": SDL_SCANCODE_INSERT,
    "ins": SDL_SCANCODE_INSERT,
    "delete": SDL_SCANCODE_DELETE,
    "del": SDL_SCANCODE_DELETE,
    "home": SDL_SCANCODE_HOME,
    "end": SDL_SCANCODE_END,
    "pageup": SDL_SCANCODE_PAGEUP,
    "page up": SDL_SCANCODE_PAGEUP,
    "pagedown": SDL_SCANCODE_PAGEDOWN,
    "page down": SDL_SCANCODE_PAGEDOWN,
    "up": SDL_SCANCODE_UP,
    "down": SDL_SCANCODE_DOWN,
    "left": SDL_SCANCODE_LEFT,
    "right": SDL_SCANCODE_RIGHT,
}
