from sdl2 import *
speshs = {
    " ": SDLK_SPACE,
    "space": SDLK_SPACE,
    "\t": SDLK_TAB,
    "tab": SDLK_TAB,
    "enter": SDLK_RETURN,
    "return": SDLK_RETURN,
    "\n": SDLK_RETURN,
    "\r": SDLK_RETURN,
    "backspace": SDLK_BACKSPACE,
    "back": SDLK_BACKSPACE,
    "\b": SDLK_BACKSPACE,
    "escape": SDLK_ESCAPE,
    "esc": SDLK_ESCAPE,
    "\033": SDLK_ESCAPE,
    "insert": SDLK_INSERT,
    "ins": SDLK_INSERT,
    "delete": SDLK_DELETE,
    "del": SDLK_DELETE,
    "home": SDLK_HOME,
    "end": SDLK_END,
    "pageup": SDLK_PAGEUP,
    "pagedown": SDLK_PAGEDOWN,
    "up": SDLK_UP,
    "down": SDLK_DOWN,
    "left": SDLK_LEFT,
    "right": SDLK_RIGHT,
}
