from __future__ import annotations

import numpy as np


class TransBase:

    def _warpPs(self, mat: np.ndarray, points: np.ndarray):
        ...

    def _regMat(self, mat: np.ndarray):
        """Returns True if a matrix is 'regular' - no rotations or perspective warps"""

    def _affMat(self, mat: np.ndarray):
        """Returns True if a matrix is 'affine' - no perspective warps"""

    def _regWarp(self, mat: np.ndarray, p, offset: bool=True):
        """Warps a point assuming no perspective warp (bottom row is [0, 0, 1])"""

# This file was generated by stubgen-pyx v0.2.1 from /home/grapefru14/Documents/Blaze-Sudio/BlazeSudio/graphicsCore/_basey/init.pyx