from __future__ import annotations

import numpy as np
import numpy as cnp

__cimport_types__ = [cnp.ndarray]

class Base:

    def _regMat(self, mat: cnp.ndarray) -> bool:
        """Returns True if a matrix is 'regular' - no rotations or perspective warps"""

    def _affMat(self, mat: cnp.ndarray) -> bool:
        """Returns True if a matrix is 'affine' - no perspective warps"""

    def _regWarp(self, mat: cnp.ndarray, p: object, offset: bool=True) -> cnp.ndarray:
        """Warps a point assuming no perspective warp (bottom row is [0, 0, 1])"""

    def _warpbbx(self, mat: cnp.ndarray, crop: object, outercrop: object) -> object:
        ...

    def _warpPs(self, mat: np.ndarray, points: np.ndarray):
        ...

# This file was generated by stubgen-pyx v0.2.1 from /home/grapefru14/Documents/Blaze-Sudio/BlazeSudio/graphicsCore/_basey/init.pyx