from __future__ import annotations

import numpy as cnp

__cimport_types__ = [cnp.ndarray]

def blit(mat: cnp.ndarray, src: cnp.ndarray, dst: cnp.ndarray, crop):
    ...

# This file was generated by stubgen-pyx v0.2.1 from /home/grapefru14/Documents/Blaze-Sudio/BlazeSudio/graphicsCore/_blit/__init__.pyx