from __future__ import annotations


class Timer:

    def __cinit__(self):
        ...

# This file was generated by stubgen-pyx v0.2.1 from /home/grapefru14/Documents/Blaze-Sudio/BlazeSudio/speed/time/__init__.pyx