import numpy as np
from numpy import ndarray

__path__: list

def _drawCirc(arr: np.ndarray, pos: np.ndarray, radius: int, thickness: int, col: np.ndarray):
    ...

def _drawElipse(arr: np.ndarray, pos: np.ndarray, xradius: int, yradius: int, rotation: float, thickness: int, col: np.ndarray):
    ...

def _drawRect(arr: ndarray, pos: ndarray, sze: ndarray, thickness: float, round: float, col: ndarray):
    ...

def _drawThickLine(arr: ndarray, p1: ndarray, p2: ndarray, thickness: float, colour: ndarray):
    ...

def apply(mat: np.ndarray, arr: np.ndarray, smooth: bool):
    ...


# This file was generated by stubgen-pyx v0.1.3