import numpy as np

__path__: list

def _drawCirc(arr: np.ndarray, pos: np.ndarray, radius: int, thickness: int, col: np.ndarray):
    ...

def _drawElipse(arr: np.ndarray, pos: np.ndarray, xradius: int, yradius: int, rotation: float, thickness: int, col: np.ndarray):
    ...

def _drawRect(arr: np.ndarray, pos: float[:], sze: float[:], thickness: float, round: float, col: np.ndarray):
    ...

def _drawThickLine(arr: np.ndarray, p1: float[:], p2: float[:], thickness: float, colour: np.ndarray):
    ...

def apply(mat: np.ndarray, arr: np.ndarray, smooth: bool):
    ...


# This file was generated by stubgen-pyx v0.1.3