from numpy import ndarray

__path__: list

def drawCirc(arr: ndarray, pos: float[:], radius: float, thickness: float, col: ndarray):
    ...

def drawElipse(arr: ndarray, pos: float[:], xradius: float, yradius: float, rotation: float, thickness: float, col: ndarray):
    ...

def drawLine(arr: ndarray, p1: float[:], p2: float[:], thickness: float, colour: ndarray):
    ...

def drawPolyLine(arr: ndarray, points: float[:, _:], thickness: float, col: ndarray, round: bool):
    ...

def drawRect(arr: ndarray, pos: float[:], sze: float[:], thickness: float, round: float, col: ndarray):
    ...


# This file was generated by stubgen-pyx v0.1.3