from __future__ import annotations

import numpy as cnp

__cimport_types__ = [cnp.ndarray]

def drawLine(arr: cnp.ndarray, p1: memoryview, p2: memoryview, thickness: float, col: cnp.ndarray, crop):
    ...

def drawPolyLine(arr: cnp.ndarray, points: memoryview, thickness: float, col: cnp.ndarray, crop, round: bool):
    ...

def drawRect(arr: cnp.ndarray, pos: memoryview, sze: memoryview, thickness: float, round: float, col: cnp.ndarray, crop):
    ...

def drawCirc(arr: cnp.ndarray, pos: memoryview, radius: float, thickness: float, col: cnp.ndarray, crop):
    ...

def drawElipse(arr: cnp.ndarray, pos: memoryview, xradius: float, yradius: float, rotation: float, thickness: float, col: cnp.ndarray, crop):
    ...

# This file was generated by stubgen-pyx v0.2.1 from /home/grapefru14/Documents/Blaze-Sudio/BlazeSudio/graphicsCore/_calcs/init.pyx